### ISSUE TITLE
How to implement manage attaching and detaching nested relationships?

### ISSUE THREAD

**Issue by devmansurov** [daftspunk/oc-formist-plugin#6]
I looked at an [example here](https://octobercms.com/support/article/ob-21) for creating data using nested relationships, but I didn’t understand how to manage the attachment and detachment of nested relationship data.

How to create and make partials correctly in this case?

OctoberCMS version: 2.x (not 3.x)

**Comment by daftspunk** [comment]
Hi @devmansurov 

We recommend updating to v3.x if possible since it supports nested relations natively now.

However, if you are interested in learning, the `add` and `remove` methods can be called on the relation object to manage the attachments and pivot data.

```php
->add($model, null, ['pivot' => 'data']);
```

The relation controller also supports an interface for managing this data via the `pivot[field]` syntax.

I hope this helps.
